module.exports = {
  data: [
    // --- Web Technologies ---
    {
      question: "What does HTML stand for?",
      option1: "Hyper Text Markup Language",
      option2: "High Transfer Machine Language",
      option3: "Hyperlink and Text Management Language",
      option4: "Home Tool Markup Language",
      ans: 1,
    },
    {
      question: "Which CSS property is used to change text color?",
      option1: "font-style",
      option2: "color",
      option3: "text-color",
      option4: "background-color",
      ans: 2,
    },
    {
      question: "Which JavaScript keyword is used to declare a constant?",
      option1: "var",
      option2: "let",
      option3: "const",
      option4: "static",
      ans: 3,
    },

    // --- Linux & Networking ---
    {
      question: "Which command is used to list files in Linux?",
      option1: "ls",
      option2: "dir",
      option3: "show",
      option4: "list",
      ans: 1,
    },
    {
      question: "Which protocol is primarily used for secure communication over the internet?",
      option1: "HTTP",
      option2: "HTTPS",
      option3: "FTP",
      option4: "SMTP",
      ans: 2,
    },
    {
      question: "What does DNS stand for?",
      option1: "Domain Name System",
      option2: "Data Network Service",
      option3: "Digital Node Server",
      option4: "Domain Number Setup",
      ans: 1,
    },
    {
      question: "Which port does SSH use by default?",
      option1: "21",
      option2: "22",
      option3: "80",
      option4: "443",
      ans: 2,
    },

    // --- Git & Version Control ---
    {
      question: "In Git, which command is used to create a new branch?",
      option1: "git branch <branch-name>",
      option2: "git checkout <branch-name>",
      option3: "git init <branch-name>",
      option4: "git merge <branch-name>",
      ans: 1,
    },
    {
      question: "Which of the following is a version control system?",
      option1: "Docker",
      option2: "Git",
      option3: "Kubernetes",
      option4: "Jenkins",
      ans: 2,
    },
    {
      question: "Which command is used to upload local changes to GitHub?",
      option1: "git fetch",
      option2: "git pull",
      option3: "git push",
      option4: "git clone",
      ans: 3,
    },

    // --- Cloud ---
    {
      question: "Which AWS service is used to store objects like images and files?",
      option1: "EC2",
      option2: "RDS",
      option3: "S3",
      option4: "Lambda",
      ans: 3,
    },
    {
      question: "Which cloud provider offers services like EC2, S3, and Lambda?",
      option1: "Google Cloud",
      option2: "AWS",
      option3: "Azure",
      option4: "IBM Cloud",
      ans: 2,
    },
    {
      question: "Which Azure service is equivalent to AWS EC2?",
      option1: "Azure Functions",
      option2: "Azure VM",
      option3: "Azure Blob Storage",
      option4: "Azure SQL Database",
      ans: 2,
    },
    {
      question: "Which Google Cloud service is used for serverless computing?",
      option1: "Cloud Run",
      option2: "Cloud Functions",
      option3: "App Engine",
      option4: "All of the above",
      ans: 4,
    },

    // --- DevOps ---
    {
      question: "Docker is mainly used for?",
      option1: "Virtual Machines",
      option2: "Containerization",
      option3: "Networking",
      option4: "Load Balancing",
      ans: 2,
    },
    {
      question: "In Kubernetes, what does 'pod' represent?",
      option1: "A cluster of nodes",
      option2: "A single container",
      option3: "A group of one or more containers",
      option4: "A virtual machine",
      ans: 3,
    },
    {
      question: "Terraform is used for?",
      option1: "Application Deployment",
      option2: "Infrastructure as Code",
      option3: "Database Management",
      option4: "Containerization",
      ans: 2,
    },
    {
      question: "Which DevOps tool is used for automation and pipelines?",
      option1: "Jenkins",
      option2: "Prometheus",
      option3: "Grafana",
      option4: "Ansible",
      ans: 1,
    },
    {
      question: "Which configuration management tool uses YAML playbooks?",
      option1: "Ansible",
      option2: "Chef",
      option3: "Puppet",
      option4: "SaltStack",
      ans: 1,
    },
    {
      question: "Prometheus is mainly used for?",
      option1: "Monitoring",
      option2: "Logging",
      option3: "CI/CD",
      option4: "Containerization",
      ans: 1,
    },

    // --- Databases ---
    {
      question: "Which of the following is a NoSQL database?",
      option1: "MySQL",
      option2: "PostgreSQL",
      option3: "MongoDB",
      option4: "OracleDB",
      ans: 3,
    },
    {
      question: "Which SQL command is used to retrieve data?",
      option1: "INSERT",
      option2: "UPDATE",
      option3: "SELECT",
      option4: "DELETE",
      ans: 3,
    },
    {
      question: "Which database service is serverless in AWS?",
      option1: "RDS",
      option2: "Aurora",
      option3: "DynamoDB",
      option4: "Redshift",
      ans: 3,
    },

    // --- Programming ---
    {
      question: "Which company developed the Java programming language?",
      option1: "Microsoft",
      option2: "Sun Microsystems",
      option3: "IBM",
      option4: "Oracle",
      ans: 2,
    },
    {
      question: "Which programming language is primarily used for data science?",
      option1: "C",
      option2: "Java",
      option3: "Python",
      option4: "PHP",
      ans: 3,
    },
    {
      question: "Which keyword is used in Java to inherit a class?",
      option1: "this",
      option2: "super",
      option3: "extends",
      option4: "implements",
      ans: 3,
    },
    {
      question: "Which symbol is used for comments in Python?",
      option1: "//",
      option2: "#",
      option3: "/* */",
      option4: "<!-- -->",
      ans: 2,
    },
    {
      question: "What does OOP stand for?",
      option1: "Object-Oriented Programming",
      option2: "Open Operating Program",
      option3: "Optimized Object Processing",
      option4: "Optional Object Protocol",
      ans: 1,
    },

    // --- Security & General IT ---
    {
      question: "Which HTTP status code means 'Not Found'?",
      option1: "200",
      option2: "301",
      option3: "404",
      option4: "500",
      ans: 3,
    },
    {
      question: "Which encryption protocol is used in HTTPS?",
      option1: "SSL/TLS",
      option2: "AES",
      option3: "RSA",
      option4: "SHA",
      ans: 1,
    },
    {
      question: "What does 'phishing' refer to?",
      option1: "Network monitoring",
      option2: "Stealing user data via fake websites",
      option3: "Email encryption",
      option4: "Database replication",
      ans: 2,
    },
    {
      question: "Which type of attack involves overwhelming a system with requests?",
      option1: "Phishing",
      option2: "Man-in-the-Middle",
      option3: "DDoS",
      option4: "SQL Injection",
      ans: 3,
    },
    {
      question: "Which operating system is open-source?",
      option1: "Windows",
      option2: "macOS",
      option3: "Linux",
      option4: "ChromeOS",
      ans: 3,
    },
  ],
};
